// <auto-generated />
using DataAccessLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(CustomerCurrencyDbContext))]
    partial class CustomerCurrencyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DataAccessLayer.CutomerCurrencyEntity", b =>
                {
                    b.Property<long>("CustomerTransactionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CustomerTransactionID"), 1L, 1);

                    b.Property<double>("amount")
                        .HasColumnType("float");

                    b.Property<string>("fromCurrency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("toCurrency")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerTransactionID");

                    b.ToTable("cutomerCurrencyEntities");
                });
#pragma warning restore 612, 618
        }
    }
}
